graph TD
    %% N0 - EIXOS
    N0_SINTRÓPICO[Eixo SINTRÓPICO<br/>N0]
    N0_ENTRÓPICO[Eixo ENTRÓPICO<br/>N0]
    
    %% N1 - PILARES
    N1_LOGOS[LOGOS<br/>N1]
    N1_BIOS[BIOS<br/>N1]
    N1_PATHOS[PATHOS<br/>N1]
    N1_KHAOS[KHAOS<br/>N1]
    N1_APEIRON[APEIRON<br/>N1]
    N1_MYTHOS[MYTHOS<br/>N1]
    
    %% N0 -> N1
    N0_SINTRÓPICO --> N1_LOGOS
    N0_SINTRÓPICO --> N1_BIOS
    N0_SINTRÓPICO --> N1_PATHOS
    N0_ENTRÓPICO --> N1_KHAOS
    N0_ENTRÓPICO --> N1_APEIRON
    N0_ENTRÓPICO --> N1_MYTHOS
    
    %% N2 - DOMÍNIOS
    N2_1_1[N2: 1.1 ALGORITMIA]
    N2_1_2[N2: 1.2 NOMOS]
    N2_1_3[N2: 1.3 MECÂNICA]
    N2_2_1[N2: 2.1 OIKOS]
    N2_2_2[N2: 2.2 SOMA]
    N2_2_3[N2: 2.3 METABOLISMO]
    N2_3_1[N2: 3.1 ETHOS]
    N2_3_2[N2: 3.2 ALTERIDADE]
    N2_3_3[N2: 3.3 ESTÉTICA]
    N2_4_1[N2: 4.1 ENTROPIA]
    N2_4_2[N2: 4.2 SINGULARIDADE]
    N2_4_3[N2: 4.3 SÍNTESE]
    N2_5_1[N2: 5.1 ESCALA]
    N2_5_2[N2: 5.2 VIBRATIO]
    N2_5_3[N2: 5.3 VÁCUO]
    N2_6_1[N2: 6.1 ARQUÉTIPO]
    N2_6_2[N2: 6.2 NARRATIVA]
    N2_6_3[N2: 6.3 MISTÉRIO]
    
    N1_LOGOS --> N2_1_1
    N1_LOGOS --> N2_1_2
    N1_LOGOS --> N2_1_3
    N1_BIOS --> N2_2_1
    N1_BIOS --> N2_2_2
    N1_BIOS --> N2_2_3
    N1_PATHOS --> N2_3_1
    N1_PATHOS --> N2_3_2
    N1_PATHOS --> N2_3_3
    N1_KHAOS --> N2_4_1
    N1_KHAOS --> N2_4_2
    N1_KHAOS --> N2_4_3
    N1_APEIRON --> N2_5_1
    N1_APEIRON --> N2_5_2
    N1_APEIRON --> N2_5_3
    N1_MYTHOS --> N2_6_1
    N1_MYTHOS --> N2_6_2
    N1_MYTHOS --> N2_6_3
    
    %% N3 - SUBÁRVORES (54 total)
    N3_1_1_1[N3: 1.1.1 RESOLUÇÃO]
    N3_1_1_2[N3: 1.1.2 OPTIMIZAÇÃO]
    N3_1_1_3[N3: 1.1.3 VALIDAÇÃO]
    N3_1_2_1[N3: 1.2.1 LEGISLAÇÃO]
    N3_1_2_2[N3: 1.2.2 CONTORNO]
    N3_1_2_3[N3: 1.2.3 PACTO]
    N3_1_3_1[N3: 1.3.1 ESTÁTICA]
    N3_1_3_2[N3: 1.3.2 DINÂMICA]
    N3_1_3_3[N3: 1.3.3 TERMOTRANSDINÂMICA]
    N3_2_1_1[N3: 2.1.1 MORADA]
    N3_2_1_2[N3: 2.1.2 TERRITÓRIO]
    N3_2_1_3[N3: 2.1.3 PROVISÃO]
    N3_2_2_1[N3: 2.2.1 INTEGRIDADE]
    N3_2_2_2[N3: 2.2.2 VITALIDADE]
    N3_2_2_3[N3: 2.2.3 HOMEOSTASE]
    N3_2_3_1[N3: 2.3.1 ANABOLISMO]
    N3_2_3_2[N3: 2.3.2 CATABOLISMO]
    N3_2_3_3[N3: 2.3.3 CICLO]
    N3_3_1_1[N3: 3.1.1 VALORES]
    N3_3_1_2[N3: 3.1.2 VIRTUDE]
    N3_3_1_3[N3: 3.1.3 RESPONSABILIDADE]
    N3_3_2_1[N3: 3.2.1 RECONHECIMENTO]
    N3_3_2_2[N3: 3.2.2 EMPATIA]
    N3_3_2_3[N3: 3.2.3 DIÁLOGO]
    N3_3_3_1[N3: 3.3.1 HARMONIA]
    N3_3_3_2[N3: 3.3.2 EXPRESSÃO]
    N3_3_3_3[N3: 3.3.3 IMPACTO]
    N3_4_1_1[N3: 4.1.1 DEGRADAÇÃO]
    N3_4_1_2[N3: 4.1.2 DISSIPAÇÃO]
    N3_4_1_3[N3: 4.1.3 CAOS]
    N3_4_2_1[N3: 4.2.1 EXCEÇÃO]
    N3_4_2_2[N3: 4.2.2 INFINITO]
    N3_4_2_3[N3: 4.2.3 TRANSFORMAÇÃO]
    N3_4_3_1[N3: 4.3.1 FUSÃO]
    N3_4_3_2[N3: 4.3.2 HIBRIDISMO]
    N3_4_3_3[N3: 4.3.3 TRANSCENDÊNCIA]
    N3_5_1_1[N3: 5.1.1 PROPORÇÃO]
    N3_5_1_2[N3: 5.1.2 MAGNITUDE]
    N3_5_1_3[N3: 5.1.3 LEI]
    N3_5_2_1[N3: 5.2.1 FREQUÊNCIA]
    N3_5_2_2[N3: 5.2.2 RESSONÂNCIA]
    N3_5_2_3[N3: 5.2.3 ONDA]
    N3_5_3_1[N3: 5.3.1 POTENCIAL]
    N3_5_3_2[N3: 5.3.2 SILÊNCIO]
    N3_5_3_3[N3: 5.3.3 CAMPO]
    N3_6_1_1[N3: 6.1.1 PADRÃO_PRIMORDIAL]
    N3_6_1_2[N3: 6.1.2 COMPORTAMENTO]
    N3_6_1_3[N3: 6.1.3 SÍMBOLO]
    N3_6_2_1[N3: 6.2.1 TEIA]
    N3_6_2_2[N3: 6.2.2 LINHA_SENTIDO]
    N3_6_2_3[N3: 6.2.3 HISTÓRIA_VIVIDA]
    N3_6_3_1[N3: 6.3.1 INCOMPREENSÃO]
    N3_6_3_2[N3: 6.3.2 INTUIÇÃO]
    N3_6_3_3[N3: 6.3.3 REVELAÇÃO]
    
    %% N2 -> N3 connections
    N2_1_1 --> N3_1_1_1
    N2_1_1 --> N3_1_1_2
    N2_1_1 --> N3_1_1_3
    N2_1_2 --> N3_1_2_1
    N2_1_2 --> N3_1_2_2
    N2_1_2 --> N3_1_2_3
    N2_1_3 --> N3_1_3_1
    N2_1_3 --> N3_1_3_2
    N2_1_3 --> N3_1_3_3
    N2_2_1 --> N3_2_1_1
    N2_2_1 --> N3_2_1_2
    N2_2_1 --> N3_2_1_3
    N2_2_2 --> N3_2_2_1
    N2_2_2 --> N3_2_2_2
    N2_2_2 --> N3_2_2_3
    N2_2_3 --> N3_2_3_1
    N2_2_3 --> N3_2_3_2
    N2_2_3 --> N3_2_3_3
    N2_3_1 --> N3_3_1_1
    N2_3_1 --> N3_3_1_2
    N2_3_1 --> N3_3_1_3
    N2_3_2 --> N3_3_2_1
    N2_3_2 --> N3_3_2_2
    N2_3_2 --> N3_3_2_3
    N2_3_3 --> N3_3_3_1
    N2_3_3 --> N3_3_3_2
    N2_3_3 --> N3_3_3_3
    N2_4_1 --> N3_4_1_1
    N2_4_1 --> N3_4_1_2
    N2_4_1 --> N3_4_1_3
    N2_4_2 --> N3_4_2_1
    N2_4_2 --> N3_4_2_2
    N2_4_2 --> N3_4_2_3
    N2_4_3 --> N3_4_3_1
    N2_4_3 --> N3_4_3_2
    N2_4_3 --> N3_4_3_3
    N2_5_1 --> N3_5_1_1
    N2_5_1 --> N3_5_1_2
    N2_5_1 --> N3_5_1_3
    N2_5_2 --> N3_5_2_1
    N2_5_2 --> N3_5_2_2
    N2_5_2 --> N3_5_2_3
    N2_5_3 --> N3_5_3_1
    N2_5_3 --> N3_5_3_2
    N2_5_3 --> N3_5_3_3
    N2_6_1 --> N3_6_1_1
    N2_6_1 --> N3_6_1_2
    N2_6_1 --> N3_6_1_3
    N2_6_2 --> N3_6_2_1
    N2_6_2 --> N3_6_2_2
    N2_6_2 --> N3_6_2_3
    N2_6_3 --> N3_6_3_1
    N2_6_3 --> N3_6_3_2
    N2_6_3 --> N3_6_3_3
    
    %% N4 - CÉLULAS (162 total - 3 por N3)
    %% ALGORITMIA
    N4_1_1_1_A[N4: R1.1.1-A DECOMPOSIÇÃO_BINÁRIA]
    N4_1_1_1_B[N4: R1.1.1-B SEQUÊNCIA_OTIMIZADA]
    N4_1_1_1_C[N4: R1.1.1-C CASO_BASE]
    N4_1_1_2_A[N4: R1.1.2-A COMPLEXIDADE_TEMPORAL]
    N4_1_1_2_B[N4: R1.1.2-B MEMOIZAÇÃO]
    N4_1_1_2_C[N4: R1.1.2-C PARALELIZAÇÃO]
    N4_1_1_3_A[N4: R1.1.3-A VERIFICAÇÃO_LÓGICA]
    N4_1_1_3_B[N4: R1.1.3-B TESTE_DE_FRONTEIRA]
    N4_1_1_3_C[N4: R1.1.3-C CORREÇÃO_PARCIAL]
    
    %% NOMOS
    N4_1_2_1_A[N4: R1.2.1-A CODIFICAÇÃO_NORMA]
    N4_1_2_1_B[N4: R1.2.1-B VERIFICAÇÃO_CONFORMIDADE]
    N4_1_2_1_C[N4: R1.2.1-C HIERARQUIA_LEIS]
    N4_1_2_2_A[N4: R1.2.2-A DEFINIÇÃO_FRONTEIRA]
    N4_1_2_2_B[N4: R1.2.2-B GESTÃO_CONTORNO]
    N4_1_2_2_C[N4: R1.2.2-C EXPANSÃO_CONTORNO]
    N4_1_2_3_A[N4: R1.2.3-A ESTABELECIMENTO_PACTO]
    N4_1_2_3_B[N4: R1.2.3-B CUMPRIMENTO_PACTO]
    N4_1_2_3_C[N4: R1.2.3-C RESOLUÇÃO_VIOLAÇÃO]
    
    %% MECÂNICA
    N4_1_3_1_A[N4: R1.3.1-A ANÁLISE_ESTÁTICA]
    N4_1_3_1_B[N4: R1.3.1-B EQUILÍBRIO_FORÇAS]
    N4_1_3_1_C[N4: R1.3.1-C REPOUSO_RELATIVO]
    N4_1_3_2_A[N4: R1.3.2-A ANÁLISE_DINÂMICA]
    N4_1_3_2_B[N4: R1.3.2-B TRANSFORMAÇÃO_ESTADOS]
    N4_1_3_2_C[N4: R1.3.2-C ENERGIA_CINÉTICA]
    N4_1_3_3_A[N4: R1.3.3-A BALANÇO_ENERGIA]
    N4_1_3_3_B[N4: R1.3.3-B EFICIÊNCIA_TERMODINÂMICA]
    N4_1_3_3_C[N4: R1.3.3-C ENTROPIA_PROCESSO]
    
    %% OIKOS
    N4_2_1_1_A[N4: B2.1.1-A PROTEÇÃO_FÍSICA]
    N4_2_1_1_B[N4: B2.1.1-B RECURSOS_ESSENCIAIS]
    N4_2_1_1_C[N4: B2.1.1-C SANEAMENTO]
    N4_2_1_2_A[N4: B2.1.2-A REIVINDICAÇÃO_ESPACIAL]
    N4_2_1_2_B[N4: B2.1.2-B DEFESA_TERRITORIAL]
    N4_2_1_2_C[N4: B2.1.2-C GESTÃO_RECURSOS_TERRITORIAIS]
    N4_2_1_3_A[N4: B2.1.3-A ARMAZENAMENTO_RECURSOS]
    N4_2_1_3_B[N4: B2.1.3-B ROTAÇÃO_ESTOQUE]
    N4_2_1_3_C[N4: B2.1.3-C DISTRIBUIÇÃO_RECURSOS]
    
    %% SOMA
    N4_2_2_1_A[N4: B2.2.1-A MANUTENÇÃO_ESTRUTURAL]
    N4_2_2_1_B[N4: B2.2.1-B AVALIAÇÃO_CONDIÇÃO]
    N4_2_2_1_C[N4: B2.2.1-C ATUALIZAÇÃO_SISTEMA]
    N4_2_2_2_A[N4: B2.2.2-A ENERGIA_VITAL]
    N4_2_2_2_B[N4: B2.2.2-B AUTORREPARAÇÃO]
    N4_2_2_2_C[N4: B2.2.2-C RESILIÊNCIA]
    N4_2_2_3_A[N4: B2.2.3-A REGULAÇÃO_INTERNA]
    N4_2_2_3_B[N4: B2.2.3-B FEEDBACK_NEGATIVO]
    N4_2_2_3_C[N4: B2.2.3-C ADAPTAÇÃO_CÍCLICA]
    
    %% METABOLISMO
    N4_2_3_1_A[N4: B2.3.1-A SÍNTESE_MATERIAL]
    N4_2_3_1_B[N4: B2.3.1-B CRESCIMENTO]
    N4_2_3_1_C[N4: B2.3.1-C COMPLEXIFICAÇÃO]
    N4_2_3_2_A[N4: B2.3.2-A DECOMPOSIÇÃO_MATERIAL]
    N4_2_3_2_B[N4: B2.3.2-B LIBERAÇÃO_ENERGIA]
    N4_2_3_2_C[N4: B2.3.2-C REMOÇÃO_DESEJOS]
    N4_2_3_3_A[N4: B2.3.3-A RECIRCULAÇÃO_MATERIAL]
    N4_2_3_3_B[N4: B2.3.3-B RENOVAÇÃO_CONTÍNUA]
    N4_2_3_3_C[N4: B2.3.3-C FLUXO_PERENE]
    
    %% ETHOS
    N4_3_1_1_A[N4: P3.1.1-A ALINHAMENTO_VALORES]
    N4_3_1_1_B[N4: P3.1.1-B CONFLITO_VALORES]
    N4_3_1_1_C[N4: P3.1.1-C TRANSPARÊNCIA]
    N4_3_1_2_A[N4: P3.1.2-A EXCELÊNCIA_MORAL]
    N4_3_1_2_B[N4: P3.1.2-B CARÁTER]
    N4_3_1_2_C[N4: P3.1.2-C INTEGRIDADE]
    N4_3_1_3_A[N4: P3.1.3-A DEVER]
    N4_3_1_3_B[N4: P3.1.3-B CONSEQUÊNCIA]
    N4_3_1_3_C[N4: P3.1.3-C ESCOLHA]
    
    %% ALTERIDADE
    N4_3_2_1_A[N4: P3.2.1-A VALIDAÇÃO_EXISTÊNCIA]
    N4_3_2_1_B[N4: P3.2.1-B DIGNIDADE]
    N4_3_2_1_C[N4: P3.2.1-C EXISTÊNCIA]
    N4_3_2_2_A[N4: P3.2.2-A COMPREENSÃO_PROFUNDA]
    N4_3_2_2_B[N4: P3.2.2-B PONTE]
    N4_3_2_2_C[N4: P3.2.2-C SENTIDO]
    N4_3_2_3_A[N4: P3.2.3-A TROCA_MÚTUA]
    N4_3_2_3_B[N4: P3.2.3-B CONSTRUÇÃO_CONJUNTA]
    N4_3_2_3_C[N4: P3.2.3-C REVELAÇÃO]
    
    %% ESTÉTICA
    N4_3_3_1_A[N4: P3.3.1-A PROPORÇÃO_AUREA]
    N4_3_3_1_B[N4: P3.3.1-B EQUILÍBRIO_ESTÉTICO]
    N4_3_3_1_C[N4: P3.3.1-C RESSONÂNCIA]
    N4_3_3_2_A[N4: P3.3.2-A FORMA_CORPO]
    N4_3_3_2_B[N4: P3.3.2-B EXTERIORIZAÇÃO]
    N4_3_3_2_C[N4: P3.3.2-C LINGUAGEM_ESTÉTICA]
    N4_3_3_3_A[N4: P3.3.3-A TRANSFORMAÇÃO]
    N4_3_3_3_B[N4: P3.3.3-B EMOCIONAL]
    N4_3_3_3_C[N4: P3.3.3-C LIBERDADE]
    
    %% ENTROPIA
    N4_4_1_1_A[N4: K4.1.1-A ENTROPIA_SISTEMA]
    N4_4_1_1_B[N4: K4.1.1-B DESTRUIÇÃO_CRIATIVA]
    N4_4_1_1_C[N4: K4.1.1-C RECICLAGEM]
    N4_4_1_2_A[N4: K4.1.2-A DISPERSÃO_ENERGIA]
    N4_4_1_2_B[N4: K4.1.2-B ENTROPIA_AUMENTADA]
    N4_4_1_2_C[N4: K4.1.2-C RETORNO_AMORFO]
    N4_4_1_3_A[N4: K4.1.3-A ALEATORIEDADE]
    N4_4_1_3_B[N4: K4.1.3-B COMPLEXIDADE_CAÓTICA]
    N4_4_1_3_C[N4: K4.1.3-C PADRÕES_EMERGENTES]
    
    %% SINGULARIDADE
    N4_4_2_1_A[N4: K4.2.1-A PONTO_EXCEPCIONAL]
    N4_4_2_1_B[N4: K4.2.1-B LEI_SUPERIOR]
    N4_4_2_1_C[N4: K4.2.1-C TRANSFORMAÇÃO_EXCEPCIONAL]
    N4_4_2_2_A[N4: K4.2.2-A HORIZONTE_INATINGÍVEL]
    N4_4_2_2_B[N4: K4.2.2-B POTENCIAL_INFINITO]
    N4_4_2_2_C[N4: K4.2.2-C EXPANSÃO_CONTÍNUA]
    N4_4_2_3_A[N4: K4.2.3-A MORTE_E_RENASCIMENTO]
    N4_4_2_3_B[N4: K4.2.3-B MUDANÇA_RADICAL]
    N4_4_2_3_C[N4: K4.2.3-C NOVA_ORDEM]
    
    %% SÍNTESE
    N4_4_3_1_A[N4: K4.3.1-A UNIÃO_ELEMENTOS]
    N4_4_3_1_B[N4: K4.3.1-B SÍNTESE_CRIATIVA]
    N4_4_3_1_C[N4: K4.3.1-C TRANSCENDÊNCIA]
    N4_4_3_2_A[N4: K4.3.2-A MISTURA_PRESERVAÇÃO]
    N4_4_3_2_B[N4: K4.3.2-B PONTE_TEMPORAL]
    N4_4_3_2_C[N4: K4.3.2-C IDENTIDADE_HÍBRIDA]
    N4_4_3_3_A[N4: K4.3.3-A SUPERAÇÃO]
    N4_4_3_3_B[N4: K4.3.3-B INCLUSÃO]
    N4_4_3_3_C[N4: K4.3.3-C NÍVEL_NOVO]
    
    %% ESCALA
    N4_5_1_1_A[N4: A5.1.1-A ESCALAMENTO]
    N4_5_1_1_B[N4: A5.1.1-B PROPORÇÃO_AUREA]
    N4_5_1_1_C[N4: A5.1.1-C ISOMORFISMO]
    N4_5_1_2_A[N4: A5.1.2-A TAMANHO_NATUREZA]
    N4_5_1_2_B[N4: A5.1.2-B EXPERIÊNCIA_ESCALAR]
    N4_5_1_2_C[N4: A5.1.2-C LEI_ESCALAR]
    N4_5_1_3_A[N4: A5.1.3-A LEI_RELATIVA]
    N4_5_1_3_B[N4: A5.1.3-B MANIFESTAÇÃO_LEI]
    N4_5_1_3_C[N4: A5.1.3-C ESCALA_APLICAÇÃO]
    
    %% VIBRATIO
    N4_5_2_1_A[N4: A5.2.1-A CICLO_TEMPORAL]
    N4_5_2_1_B[N4: A5.2.1-B RESSONÂNCIA_FREQUÊNCIA]
    N4_5_2_1_C[N4: A5.2.1-C IDENTIDADE_FREQUÊNCIA]
    N4_5_2_2_A[N4: A5.2.2-A AMPLIFICAÇÃO]
    N4_5_2_2_B[N4: A5.2.2-B SINCRONIA]
    N4_5_2_2_C[N4: A5.2.2-C MULTIPLICAÇÃO]
    N4_5_2_3_A[N4: A5.2.3-A PROPAGAÇÃO]
    N4_5_2_3_B[N4: A5.2.3-B POTENCIAL_ATUAL]
    N4_5_2_3_C[N4: A5.2.3-C PADRÃO_ONDA]
    
    %% VÁCUO
    N4_5_3_1_A[N4: A5.3.1-A CAPACIDADE_LATENTE]
    N4_5_3_1_B[N4: A5.3.1-B AVESSO_MANIFESTO]
    N4_5_3_1_C[N4: A5.3.1-C CAMPO_POTENCIAL]
    N4_5_3_2_A[N4: A5.3.2-A AUSÊNCIA_MANIFESTAÇÃO]
    N4_5_3_2_B[N4: A5.3.2-B LINGUAGEM_NÃO_MANIFESTO]
    N4_5_3_2_C[N4: A5.3.2-C PRESENÇA_ausência]
    N4_5_3_3_A[N4: A5.3.3-A MATRIZ_POSSIBILIDADES]
    N4_5_3_3_B[N4: A5.3.3-B REPOUSO_POTENCIAL]
    N4_5_3_3_C[N4: A5.3.3-C UNIFICACAO_CAMPO]
    
    %% ARQUÉTIPO
    N4_6_1_1_A[N4: M6.1.1-A RECONHECIMENTO_ARQUETÍPICO]
    N4_6_1_1_B[N4: M6.1.1-B ATIVAÇÃO_SIMPOLAR]
    N4_6_1_1_C[N4: M6.1.1-C SÍNTESE_OPOSTOS]
    N4_6_1_2_A[N4: M6.1.2-A ROTEIRO_INVISIBLE]
    N4_6_1_2_B[N4: M6.1.2-B PADRÃO_COMPORTAMENTAL]
    N4_6_1_2_C[N4: M6.1.2-C INFLUÊNCIA_ARQUETÍPICA]
    N4_6_1_3_A[N4: M6.1.3-A PONTE_SENSÍVEL]
    N4_6_1_3_B[N4: M6.1.3-B LINGUAGEM_SENSÍVEL]
    N4_6_1_3_C[N4: M6.1.3-C ARQUÉTIPO_EM_FORMA]
    
    %% NARRATIVA
    N4_6_2_1_A[N4: M6.2.1-A TEIA_CONEXÕES]
    N4_6_2_1_B[N4: M6.2.1-B TECIDO_SENTIDO]
    N4_6_2_1_C[N4: M6.2.1-C COMPLEXIDADE_TEIA]
    N4_6_2_2_A[N4: M6.2.2-A TEMPO_IDENTIDADE]
    N4_6_2_2_B[N4: M6.2.2-B NARRATIVA_VIDA]
    N4_6_2_2_C[N4: M6.2.2-C SENTIDO_TEMPORAL]
    N4_6_2_3_A[N4: M6.2.3-A EXPERIÊNCIA_NARRATIVA]
    N4_6_2_3_B[N4: M6.2.3-B CONTINUIDADE_EXPERIÊNCIA]
    N4_6_2_3_C[N4: M6.2.3-C NARRATIVA_ATIVA]
    
    %% MISTÉRIO
    N4_6_3_1_A[N4: M6.3.1-A LIMITE_ANALÍTICO]
    N4_6_3_1_B[N4: M6.3.1-B PROTEÇÃO_MISTÉRIO]
    N4_6_3_1_C[N4: M6.3.1-C HUMILDADE_CONHECIMENTO]
    N4_6_3_2_A[N4: M6.3.2-A CONHECIMENTO_DIRETO]
    N4_6_3_2_B[N4: M6.3.2-B TOCAR_PROFUNDIDADE]
    N4_6_3_2_C[N4: M6.3.2-C SABER_IMEDIATO]
    N4_6_3_3_A[N4: M6.3.3-A DESVELAMENTO]
    N4_6_3_3</tool_call>